* Generated by MPModelProtoExporter
*   Name             : 
*   Format           : Free
*   Constraints      : 7
*   Variables        : 12
*     Binary         : 12
*     Integer        : 0
*     Continuous     : 0
NAME          
ROWS
 N  COST
 E  c0
 E  c1
 E  c2
 E  c3
 E  c4
 E  c5
 E  c6
COLUMNS
  INTSTART  'MARKER'                            'INTORG'
    x12     COST         6  c0           1
    x12     c1          -1  c2          -1
    x13     COST         7  c1           1
    x13     c2          -1  c3          -1
    x13     c4          -1
    x23     COST         1  c2           1
    x23     c3          -1  c5          -1
    x24     COST         3  c3           1
    x24     c4          -1  c5          -1
    x25     COST         4  c4           1
    x25     c6          -1
    x34     COST         2  c4          -1
    x34     c5           1  c6          -1
    x36     COST         5
    x45     COST         3
    x46     COST         2
    x57     COST         7
    x65     COST         2
    x67     COST         4
  INTEND    'MARKER'                            'INTEND'
RHS
    RHS     c0           1  c1           0
    RHS     c2           0  c3           0
    RHS     c4           0  c5           0
    RHS     c6           1
BOUNDS
 BV BOUND   x12
 BV BOUND   x13
 BV BOUND   x23
 BV BOUND   x24
 BV BOUND   x25
 BV BOUND   x34
 BV BOUND   x36
 BV BOUND   x45
 BV BOUND   x46
 BV BOUND   x57
 BV BOUND   x65
 BV BOUND   x67
ENDATA
