* Generated by MPModelProtoExporter
*   Name             : 
*   Format           : Free
*   Constraints      : 10
*   Variables        : 18
*     Binary         : 18
*     Integer        : 0
*     Continuous     : 0
NAME          
ROWS
 N  COST
 G  auto_c_000000000
 G  auto_c_000000001
 E  auto_c_000000002
 E  auto_c_000000003
 E  auto_c_000000004
 E  auto_c_000000005
 E  auto_c_000000006
 G  auto_c_000000007
 G  auto_c_000000008
 G  auto_c_000000009
COLUMNS
  INTSTART  'MARKER'                            'INTORG'
    x[1][2]           COST                   2  auto_c_000000002       1
    x[1][2]           auto_c_000000003      -1  auto_c_000000007       1
    x[1][3]           COST                  10  auto_c_000000002       1
    x[1][3]           auto_c_000000004      -1  auto_c_000000007       1
    x[2][1]           COST                   2  auto_c_000000002      -1
    x[2][1]           auto_c_000000003       1  auto_c_000000008       1
    x[2][3]           COST                   5  auto_c_000000003       1
    x[2][3]           auto_c_000000004      -1  auto_c_000000008       1
    x[3][1]           COST                  10  auto_c_000000002      -1
    x[3][1]           auto_c_000000004       1  auto_c_000000009       1
    x[3][2]           COST                   5  auto_c_000000003      -1
    x[3][2]           auto_c_000000004       1  auto_c_000000009       1
    x[1][4]           auto_c_000000002       1  auto_c_000000006       1
    x[1][4]           auto_c_000000007       1
    x[0][1]           auto_c_000000002      -1  auto_c_000000005       1
    x[2][4]           auto_c_000000003       1  auto_c_000000006       1
    x[2][4]           auto_c_000000008       1
    x[0][2]           auto_c_000000003      -1  auto_c_000000005       1
    x[3][4]           auto_c_000000004       1  auto_c_000000006       1
    x[3][4]           auto_c_000000009       1
    x[0][3]           auto_c_000000004      -1  auto_c_000000005       1
    y[1]              auto_c_000000000       1  auto_c_000000007      -1
    y[2]              auto_c_000000000       1  auto_c_000000008      -1
    y[3]              auto_c_000000001       1  auto_c_000000009      -1
  INTEND    'MARKER'                            'INTEND'
RHS
    RHS               auto_c_000000000       1  auto_c_000000001       1
    RHS               auto_c_000000002       0  auto_c_000000003       0
    RHS               auto_c_000000004       0  auto_c_000000005       1
    RHS               auto_c_000000006       1  auto_c_000000007       0
    RHS               auto_c_000000008       0  auto_c_000000009       0
BOUNDS
 BV BOUND             x[1][1]
 BV BOUND             x[1][2]
 BV BOUND             x[1][3]
 BV BOUND             x[2][1]
 BV BOUND             x[2][2]
 BV BOUND             x[2][3]
 BV BOUND             x[3][1]
 BV BOUND             x[3][2]
 BV BOUND             x[3][3]
 BV BOUND             x[1][4]
 BV BOUND             x[0][1]
 BV BOUND             x[2][4]
 BV BOUND             x[0][2]
 BV BOUND             x[3][4]
 BV BOUND             x[0][3]
 BV BOUND             y[1]
 BV BOUND             y[2]
 BV BOUND             y[3]
ENDATA
